FROM node:18-alpine as build
LABEL org.opencontainers.image.source="https://github.com/Matt54633/ADP-React-Project-MS"

WORKDIR /app

COPY package*.json ./
RUN npm install && npm cache clean --force

COPY . .

EXPOSE 4000
EXPOSE 5173

CMD npm run start & npm run dev
