FROM node:18-alpine as build
LABEL org.opencontainers.image.source="https://github.com/Matt54633/ADP-React-Project-MS"

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm install -g concurrently

EXPOSE 5173 4000

CMD ["npm", "run", "app"]
