name: Run Automated tests

on:
  push:
    branches:
      [ main ]
  pull_request:
    branches:
      [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install dependencies
        working-directory: front-end-app
        run: npm ci

      - name: Run tests
        working-directory: front-end-app
        run: npm run test